<?php

return [
    'accepted' => ['code' => 'VALIDATION_ERROR_ACCEPTED'],
    'active_url' => ['code' => 'VALIDATION_ERROR_ACTIVE_URL'],
    'after' => ['code' => 'VALIDATION_ERROR_AFTER'],
    'after_or_equal' => ['code' => 'VALIDATION_ERROR_AFTER_OR_EQUAL'],
    'alpha' => ['code' => 'VALIDATION_ERROR_ALPHA'],
    'alpha_dash' => ['code' => 'VALIDATION_ERROR_ALPHA_DASH'],
    'alpha_num' => ['code' => 'VALIDATION_ERROR_ALPHA_NUM'],
    'array' => ['code' => 'VALIDATION_ERROR_ARRAY'],
    'before' => ['code' => 'VALIDATION_ERROR_BEFORE'],
    'before_or_equal' => ['code' => 'VALIDATION_ERROR_BEFORE_OR_EQUAL'],
    'between' => [
        'numeric' => ['code' => 'VALIDATION_ERROR_BETWEEN'],
        'file' => ['code' => 'VALIDATION_ERROR_BETWEEN'],
        'string' => ['code' => 'VALIDATION_ERROR_BETWEEN'],
        'array' => ['code' => 'VALIDATION_ERROR_BETWEEN'],
    ],
    'boolean' => ['code' => 'VALIDATION_ERROR_BOOLEAN'],
    'confirmed' => ['code' => 'VALIDATION_ERROR_CONFIRMED'],
    'date' => ['code' => 'VALIDATION_ERROR_DATE'],
    'date_equals' => ['code' => 'VALIDATION_ERROR_DATE_EQUALS'],
    'date_format' => ['code' => 'VALIDATION_ERROR_DATE_FORMAT'],
    'different' => ['code' => 'VALIDATION_ERROR_DIFFERENT'],
    'digits' => ['code' => 'VALIDATION_ERROR_DIGITS'],
    'digits_between' => ['code' => 'VALIDATION_ERROR_DIGITS_BETWEEN'],
    'dimensions' => ['code' => 'VALIDATION_ERROR_DIMENSIONS'],
    'distinct' => ['code' => 'VALIDATION_ERROR_DISTINCT'],
    'email' => ['code' => 'VALIDATION_ERROR_EMAIL'],
    'ends_with' => ['code' => 'VALIDATION_ERROR_ENDS_WITH'],
    'exists' => ['code' => 'VALIDATION_ERROR_EXISTS'],
    'file' => ['code' => 'VALIDATION_ERROR_FILE'],
    'filled' => ['code' => 'VALIDATION_ERROR_FILLED'],
    'gt' => [
        'numeric' => ['code' => 'VALIDATION_ERROR_GT'],
        'file' => ['code' => 'VALIDATION_ERROR_GT'],
        'string' => ['code' => 'VALIDATION_ERROR_GT'],
        'array' => ['code' => 'VALIDATION_ERROR_GT'],
    ],
    'gte' => [
        'numeric' => ['code' => 'VALIDATION_ERROR_GTE'],
        'file' => ['code' => 'VALIDATION_ERROR_GTE'],
        'string' => ['code' => 'VALIDATION_ERROR_GTE'],
        'array' => ['code' => 'VALIDATION_ERROR_GTE'],
    ],
    'image' => ['code' => 'VALIDATION_ERROR_IMAGE'],
    'in' => ['code' => 'VALIDATION_ERROR_IN'],
    'in_array' => ['code' => 'VALIDATION_ERROR_IN'],
    'integer' => ['code' => 'VALIDATION_ERROR_INTEGER'],
    'ip' => ['code' => 'VALIDATION_ERROR_IP'],
    'ipv4' => ['code' => 'VALIDATION_ERROR_IPV4'],
    'ipv6' => ['code' => 'VALIDATION_ERROR_IPV6'],
    'json' => ['code' => 'VALIDATION_ERROR_JSON'],
    'lt' => [
        'numeric' => ['code' => 'VALIDATION_ERROR_LT'],
        'file' => ['code' => 'VALIDATION_ERROR_LT'],
        'string' => ['code' => 'VALIDATION_ERROR_LT'],
        'array' => ['code' => 'VALIDATION_ERROR_LT'],
    ],
    'lte' => [
        'numeric' => ['code' => 'VALIDATION_ERROR_LTE'],
        'file' => ['code' => 'VALIDATION_ERROR_LTE'],
        'string' => ['code' => 'VALIDATION_ERROR_LTE'],
        'array' => ['code' => 'VALIDATION_ERROR_LTE'],
    ],
    'max' => [
        'numeric' => ['code' => 'VALIDATION_ERROR_MAX'],
        'file' => ['code' => 'VALIDATION_ERROR_MAX'],
        'string' => ['code' => 'VALIDATION_ERROR_MAX'],
        'array' => ['code' => 'VALIDATION_ERROR_MAX'],
    ],
    'mimes' => ['code' => 'VALIDATION_ERROR_MIMES'],
    'mimetypes' => ['code' => 'VALIDATION_ERROR_MIMETYPES'],
    'min' => [
        'numeric' => ['code' => 'VALIDATION_ERROR_MIN'],
        'file' => ['code' => 'VALIDATION_ERROR_MIN'],
        'string' => ['code' => 'VALIDATION_ERROR_MIN'],
        'array' => ['code' => 'VALIDATION_ERROR_MIN'],
    ],
    'not_in' => ['code' => 'VALIDATION_ERROR_NOT_IN'],
    'not_regex' => ['code' => 'VALIDATION_ERROR_NOT_REGEX'],
    'numeric' => ['code' => 'VALIDATION_ERROR_NUMERIC'],
    'password' => ['code' => 'VALIDATION_ERROR_PASSWORD'],
    'present' => ['code' => 'VALIDATION_ERROR_PRESENT'],
    'regex' => ['code' => 'VALIDATION_ERROR_REGEX'],
    'required' => ['code' => 'VALIDATION_ERROR_REQUIRED'],
    'required_if' => ['code' => 'VALIDATION_ERROR_REQUIRED_IF'],
    'required_unless' => ['code' => 'VALIDATION_ERROR_REQUIRED_UNLESS'],
    'required_with' => ['code' => 'VALIDATION_ERROR_REQUIRED_WITH'],
    'required_with_all' => ['code' => 'VALIDATION_ERROR_REQUIRED_WITH_ALL'],
    'required_without' => ['code' => 'VALIDATION_ERROR_REQUIRED_WITHOUT'],
    'required_without_all' => ['code' => 'VALIDATION_ERROR_REQUIRED_WITHOUT_ALL'],
    'same' => ['code' => 'VALIDATION_ERROR_SAME'],
    'size' => [
        'numeric' => ['code' => 'VALIDATION_ERROR_SIZE'],
        'file' => ['code' => 'VALIDATION_ERROR_SIZE'],
        'string' => ['code' => 'VALIDATION_ERROR_SIZE'],
        'array' => ['code' => 'VALIDATION_ERROR_SIZE'],
    ],
    'starts_with' => ['code' => 'VALIDATION_ERROR_STARTS_WITH'],
    'string' => ['code' => 'VALIDATION_ERROR_STRING'],
    'timezone' => ['code' => 'VALIDATION_ERROR_TIMEZONE'],
    'unique' => ['code' => 'VALIDATION_ERROR_UNIQUE'],
    'uploaded' => ['code' => 'VALIDATION_ERROR_UPLOADED'],
    'url' => ['code' => 'VALIDATION_ERROR_URL'],
    'uuid' => ['code' => 'VALIDATION_ERROR_UUID']
];